(function e$jscomp$0(e,d,a){function h(c,z){if(!d[c]){if(!e[c]){var f="function"==typeof require&&require;if(!z&&f)return f(c,!0);if(g)return g(c,!0);f=Error("Cannot find module '"+c+"'");throw f.code="MODULE_NOT_FOUND",f;}f=d[c]={exports:{}};e[c][0].call(f.exports,function(a){var f=e[c][1][a];return h(f?f:a)},f,f.exports,e$jscomp$0,e,d,a)}return d[c].exports}for(var g="function"==typeof require&&require,c=0;c<a.length;c++)h(a[c]);return h})({1:[function(b,e,d){var a=b("util/object"),h=b("util/Emitter");
d=e.exports=function(){h.call(this);this.height=this.width=0;(this.image=new Image).onload=this._onImageLoad.bind(this)};b=a.extend(d,h);b.load=function(a){this.image.src=a};b._onImageLoad=function(){this.width=this.image.width;this.height=this.image.height;this.emit("load",this)}},{"util/Emitter":8,"util/object":9}],2:[function(b,e,d){var a={},h=function(c){a[c.keyCode]=!0},g=function(c){a[c.keyCode]=!1};d.init=function(){window.addEventListener("keydown",h,!1);window.addEventListener("keyup",g,
!1)};d.getKeyState=function(c){return!0===a[c]}},{}],3:[function(b,e,d){d=e.exports=function(a,b){this.cells=[];this.resize(a||0,b||0)};b=d.prototype;b.resize=function(a,b){this.width=a;this.height=b;for(var g=this.cells.length=0;g<b;++g){for(var c=[],f=0;f<a;++f)c.push(0);this.cells.push(c)}};b.get=function(a,b){var g=Math.floor(a),c=Math.floor(b);return 0>g||0>c||g>=this.width||c>=this.height?-1:this.cells[c][g]};b.set=function(a,b,g){this.cells[b][a]=g}},{}],4:[function(b,e,d){d=e.exports=function(a,
b){this.set(a||0,b||0)};b=d.prototype;b.set=function(a,b){this.x=a;this.y=b;return this};b.copy=function(a){return this.set(a.x,a.y)};b.rotate=function(a){return this.set(this.x*Math.cos(a)-this.y*Math.sin(a),this.x*Math.sin(a)+this.y*Math.cos(a))};b.scale=function(a){return this.set(this.x*a,this.y*a)}},{}],5:[function(b,e,d){var a=b("util/object"),h=b("math/Vector2"),g=b("./Node"),c=b("./assets");d=e.exports=function(){g.call(this);this._zbuffer=this.textureKey=this.level=null;this.camera={position:new h(0,
0),direction:new h(1,0),plane:new h(0,.66)}};b=a.extend(d,g);b.setCamera=function(a,c,b,g){var f=this.camera;f.position.set(a,c);f.direction.set(b,g);f.plane.set(-g,b).scale(.66)};b._render=function(a){a.fillStyle="#04445C";a.fillRect(0,0,this.width,this.height/2);a.fillStyle="#008080";a.fillRect(0,this.height/2,this.width,this.height);if(this.level&&this.textureKey){var b=this.camera,g=c.getTexture(this.textureKey),f=this.level.map;this._zbuffer=Array(this.width);var d,h,e,t,n,k,l,m,u,p,v,w,x,r,
q,y;for(d=0;d<this.width;++d){h=2*d/this.width-1;e=b.position.x;t=b.position.y;n=b.direction.x+b.plane.x*h;h=b.direction.y+b.plane.y*h;k=Math.floor(e);l=Math.floor(t);p=Math.sqrt(1+h*h/(n*n));v=Math.sqrt(1+n*n/(h*h));q=r=0;0>n?(w=-1,m=(e-k)*p):(w=1,m=(k+1-e)*p);0>h?(x=-1,u=(t-l)*v):(x=1,u=(l+1-t)*v);for(;0===r;)if(m<u?(m+=p,k+=w,q=0):(u+=v,l+=x,q=1),y=f.get(k,l),0<y||-1===y)r=1;k=0===q?(k-e+(1-w)/2)/n:(l-t+(1-x)/2)/h;m=this.height/k;l=-m/2+this.height/2;m=m/2+this.height/2;e=0===q?t+k*h:e+k*n;e-=
Math.floor(e);if(0<y){e=Math.floor(128*e);if(0===q&&0>n||1===q&&0<h)e=128-e-1;e+=128*(y-1);a.drawImage(g.image,e,0,1,128,d,l,1,m-l);1===q&&(a.fillStyle="#000000",a.globalAlpha=.25,a.fillRect(d,l,1,m-l),a.globalAlpha=1)}this._zbuffer[d]=k}this._drawEntities(a)}};b._drawEntities=function(a){for(var b=this.level.entities,g=b.length,d=Array(g),h=Array(g),e=c.getTexture(this.textureKey),f=this.camera,t=f.position.x,n=f.position.y,k=0;k<g;++k){var l=b[k];d[k]=k;h[k]=(t-l.x)*(t-l.x)+(n-l.y)*(n-l.y)}d.sort(function(a,
b){return h[b]-h[a]});for(k=0;k<g;++k)for(var l=b[d[k]],m=l.x-t,u=l.y-n,p=1/(f.plane.x*f.direction.y-f.direction.x*f.plane.y),v=p*(-f.plane.y*m+f.plane.x*u),m=Math.round(this.width/2*(1+p*(f.direction.y*m-f.direction.x*u)/v)),p=Math.abs(Math.round(this.height/v)),u=-p/2+this.height/2,p=p/2+this.height/2,w=Math.abs(Math.round(this.height/v)),x=Math.round(w/2+m),r=Math.round(-w/2+m);r<x;++r)if(0<v&&0<r&&r<this.width&&v<this._zbuffer[r]){var q=Math.round(128*(r-(-w/2+m))/w),q=q+128*l.t;a.drawImage(e.image,
q,256,1,128,r,~~u,1,~~(p-u))}}},{"./Node":6,"./assets":7,"math/Vector2":4,"util/object":9}],6:[function(b,e,d){d=e.exports=function(){this.rotation=this.height=this.width=this.y=this.x=0;this.scaleY=this.scaleX=1;this.color=null};b=d.prototype;b.resize=function(a,b){this.width=a;this.height=b};b.render=function(a){a.save();var b=0!==this.rotation,g=1!==this.scaleX||1!==this.scaleY;if(b||g){var c=this.width/2,f=this.height/2;a.translate(this.x+c,this.y+f);b&&a.rotate(this.rotation);g&&a.scale(this.scaleX,
this.scaleY);a.translate(-c,-f)}else a.translate(this.x,this.y);this.color&&(a.fillStyle=this.color,a.fillRect(0,0,this.width,this.height));this._render(a);a.restore()};b._render=function(){};Object.defineProperty(b,"scale",{set:function(a){this.scaleY=this.scaleX=a}})},{}],7:[function(b,e,d){var a=b("draw/Texture"),h={},g={};d.loadTexture=function(b,f){var c=h[b]=new a;c.on("load",function(a){g[b].width=a.width;g[b].height=a.height});g[b]={texture:c,x:0,y:0,width:0,height:0};c.load(f);return c};
d.getTexture=function(a){return h[a]};d.loadTextureAtlas=function(a,b,h){a=d.loadTexture(a,b);for(var c in h)g[c]=h[c],g[c].texture=a};d.getTextureRegion=function(a){return g[a]}},{"draw/Texture":1}],8:[function(b,e,d){d=e.exports=function(){this._observers={}};b=d.prototype;b.on=function(a,b,g,c){var d=this._observers;Array.isArray(d[a])||(d[a]=[]);d[a].push({callback:b,context:g,once:!!c})};b.emit=function(a){var b=this._observers[a];if(b)for(var d=Array.prototype.slice.call(arguments,1),c=b.length-
1;0<=c;--c){var f=b[c];f.callback.apply(f.context,d);f.once&&b.splice(c,1)}}},{}],9:[function(b,e,d){d.extend=function(a,b){a.prototype=new b;a.prototype.constructor=a;a.superclass=b.prototype;return a.prototype}},{}],10:[function(b,e,d){var a=document.createElement("canvas");a.className="stage pixelated";a.width=640;a.height=360;document.body.appendChild(a);var h=a.getContext("2d");e=function(){var b=Math.min(window.innerWidth/a.width,window.innerHeight/a.height);a.style.transform="scale("+b+", "+
b+")";a.style.left=window.innerWidth/2-a.width*b/2+"px";a.style.top=window.innerHeight/2-a.height*b/2+"px"};e();window.addEventListener("resize",e,!1);var g=b("input");e=b("scene/assets");d=b("scene/FirstPerson");var c=new (b("./sim/Level"));c.init();g.init();e.loadTexture("wall","images/wall.png");var f=new d;f.resize(a.width,a.height);f.textureKey="wall";f.level=c;var z=0,A=Math.PI/2E3,B=function(a){var b=a-z;z=a;g.getKeyState(38)&&c.moveEntity(c.player,.004*b);g.getKeyState(40)&&c.moveEntity(c.player,
-.002*b);g.getKeyState(37)&&c.player.rotate(-A*b);g.getKeyState(39)&&c.player.rotate(A*b);f.setCamera(c.player.position.x,c.player.position.y,c.player.direction.x,c.player.direction.y);f.render(h);requestAnimationFrame(B)};B()},{"./sim/Level":11,input:2,"scene/FirstPerson":5,"scene/assets":7}],11:[function(b,e,d){var a=b("math/Map"),h=b("./Player");d=e.exports=function(){this.player=new h;this.map=new a;this.entities=[]};b=d.prototype;b.init=function(){this.map.resize(32,12);this.map.cells=[[1,1,
1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,2,0,0,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1],[1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1],[1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2,1,1,0,0,1,1,0,0,0,0,1,1,0,0,1,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,1,1,0,0,1,1],[1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,1,1,
0,0,0,0,1,1,0,0,1,1],[1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1],[1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]];this.player.position.set(7.5,5.5);this.player.direction.set(0,-1);this.entities.push({x:3.5,y:3.5,t:0},{x:4.5,y:4.5,t:0},{x:5.5,y:5.5,t:0},{x:3.5,y:6.5,t:0},{x:4.5,y:7.5,t:0},{x:16.5,y:5.5,t:1},{x:19.5,y:3.5,t:1})};
b.moveEntity=function(a,b){var c=a.direction.x*b,d=a.direction.y*b;0===this.map.get(a.position.x+c,a.position.y)&&(a.position.x+=c);0===this.map.get(a.position.x,a.position.y+d)&&(a.position.y+=d)}},{"./Player":12,"math/Map":3}],12:[function(b,e,d){var a=b("math/Vector2");d=e.exports=function(){this.position=new a(0,0);this.direction=new a(1,0)};d.prototype.rotate=function(a){this.direction.rotate(a)}},{"math/Vector2":4}]},{},[10]);
