var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,c){var e=this.length||0;0>b&&(b=Math.max(0,e+b));if(null==c||c>e)c=e;c=Number(c);0>c&&(c=Math.max(0,e+c));for(b=Number(b||0);b<c;b++)this[b]=a;return this}},"es6-impl","es3");
(function e$jscomp$0(d,b,c){function e(g,k){if(!b[g]){if(!d[g]){var f="function"==typeof require&&require;if(!k&&f)return f(g,!0);if(h)return h(g,!0);f=Error("Cannot find module '"+g+"'");throw f.code="MODULE_NOT_FOUND",f;}f=b[g]={exports:{}};d[g][0].call(f.exports,function(c){var b=d[g][1][c];return e(b?b:c)},f,f.exports,e$jscomp$0,d,b,c)}return b[g].exports}for(var h="function"==typeof require&&require,g=0;g<c.length;g++)e(c[g]);return e})({1:[function(a,d,b){var c=a("util/object"),e=a("util/Emitter");
b=d.exports=function(){e.call(this);this.height=this.width=0;(this.image=new Image).onload=this._onImageLoad.bind(this)};a=c.extend(b,e);a.load=function(c){this.image.src=c};a._onImageLoad=function(){this.width=this.image.width;this.height=this.image.height;this.emit("load",this)}},{"util/Emitter":11,"util/object":12}],2:[function(a,d,b){b.createSurface=function(c,a){var e=document.createElement("canvas");e.width=c;e.height=a;return e}},{}],3:[function(a,d,b){var c={},e=function(a){c[a.keyCode]=!0},
h=function(a){c[a.keyCode]=!1};b.init=function(){window.addEventListener("keydown",e,!1);window.addEventListener("keyup",h,!1)};b.getKeyState=function(a){return!0===c[a]}},{}],4:[function(a,d,b){b=d.exports=function(c,a){this.cells=[];this.resize(c||0,a||0)};a=b.prototype;a.resize=function(c,a){this.width=c;this.height=a;for(var e=this.cells.length=0;e<a;++e){for(var g=[],b=0;b<c;++b)g.push(0);this.cells.push(g)}};a.get=function(c,a){var e=Math.floor(c),g=Math.floor(a);return 0>e||0>g||e>=this.width||
g>=this.height?-1:this.cells[g][e]};a.set=function(a,e,b){this.cells[e][a]=b};a.fill=function(a){for(var c=0;c<this.height;++c)for(var b=0;b<this.width;++b)this.set(b,c,a)}},{}],5:[function(a,d,b){var c=d.exports=function(a,c,b,d,k,q,x){this.x=a||0;this.y=c||0;this.width=b||1;this.height=d||1;this.depth=k||0;this.depthLimit=q||2;this.rectLimit=x||4;this.children=[];this.rectangles=[]};c.prototype.clear=function(){for(var a=this.children,c=0,b=a.length;c<b;++c)a[c].clear();a.length=0;this.rectangles.length=
0};c.prototype.insert=function(a){var c=this.children,e=this.rectangles;if(0<c.length){var b=this._getInsertIndex(a);-1===b?e.push(a):c[b].insert(a)}else e.push(a),e.length>this.rectLimit&&this.depth<this.depthLimit&&this._divide()};c.prototype.retrieve=function(a){var c=this.rectangles.concat();if(0<this.children.length)for(var e=this._getChildren(a),b=0,d=e.length;b<d;++b)c=c.concat(e[b].retrieve(a));return c};c.prototype._divide=function(){var a=this.children,b=this.rectangles,g=Math.floor(this.width/
2),d=Math.floor(this.height/2),k=this.depth+1;a.push(new c(this.x,this.y,g,d,k,this.depthLimit,this.rectLimit));a.push(new c(this.x+g,this.y,g,d,k,this.depthLimit,this.rectLimit));a.push(new c(this.x,this.y+d,g,d,k,this.depthLimit,this.rectLimit));a.push(new c(this.x+g,this.y+d,g,d,k,this.depthLimit,this.rectLimit));this.rectangles=[];a=0;for(g=b.length;a<g;++a)this.insert(b[a])};c.prototype._getInsertIndex=function(a){var c=Math.floor(this.x+this.width/2),b=Math.floor(this.y+this.height/2);return a.x+
a.width<c?a.y+a.height<b?0:a.y>=b?2:-1:a.x>=c?a.y+a.height<b?1:a.y>=b?3:-1:-1};c.prototype._getChildren=function(a){var c=this.children,b=[],e=Math.floor(this.x+this.width/2),d=Math.floor(this.y+this.height/2);a.x<e&&(a.y<d&&b.push(c[0]),a.y+a.height>=d&&b.push(c[2]));a.x+a.width>=e&&(a.y<d&&b.push(c[1]),a.y+a.height>=d&&b.push(c[3]));return b}},{}],6:[function(a,d,b){b=d.exports=function(a,b){this.set(a||0,b||0)};a=b.prototype;a.set=function(a,b){this.x=a;this.y=b;return this};a.copy=function(a){return this.set(a.x,
a.y)};a.rotate=function(a){return this.set(this.x*Math.cos(a)-this.y*Math.sin(a),this.x*Math.sin(a)+this.y*Math.cos(a))};a.scale=function(a){return this.set(this.x*a,this.y*a)}},{}],7:[function(a,d,b){b.testCircleRect=function(a,b,d,g,f,k,q){k/=2;q/=2;a=Math.abs(a-g-k);b=Math.abs(b-f-q);if(a>k+d||b>q+d)return!1;if(a<=k||b<=q)return!0;f=a-k;b-=q;return f*f+b*b<=d*d};b.testCircleCircle=function(a,b,d,g,f,k){a-=g;b-=f;return d+k>Math.sqrt(a*a+b*b)}},{}],8:[function(a,d,b){var c=a("util/object"),e=a("math/Vector2"),
h=a("./Node"),g=a("./assets");b=d.exports=function(){h.call(this);this._zbuffer=this.textureKey=this.level=null;this.camera={position:new e(0,0),direction:new e(1,0),plane:new e(0,.666)}};a=c.extend(b,h);a.setCamera=function(a,c,b,d){var e=this.camera;e.position.set(a,c);e.direction.set(b,d);e.plane.set(-d,b).scale(.666)};a._render=function(a){if(this.level){var c=this.level.getLevelData();a.fillStyle=c.ceilColor;a.fillRect(0,0,this.width,this.height/2);a.fillStyle=c.floorColor;a.fillRect(0,this.height/
2,this.width,this.height);if(this.level&&this.textureKey){var c=this.camera,b=g.getTexture(this.textureKey),d=this.level.map;this._zbuffer=Array(this.width);var e,l,n,f,r,m,h,p,y,z,u,A,v,C,w,D;for(e=0;e<this.width;++e){l=2*e/this.width-1;n=c.position.x;f=c.position.y;r=c.direction.x+c.plane.x*l;l=c.direction.y+c.plane.y*l;m=Math.floor(n);h=Math.floor(f);z=Math.sqrt(1+l*l/(r*r));u=Math.sqrt(1+r*r/(l*l));w=C=0;0>r?(A=-1,p=(n-m)*z):(A=1,p=(m+1-n)*z);0>l?(v=-1,y=(f-h)*u):(v=1,y=(h+1-f)*u);for(;0===C;)if(p<
y?(p+=z,m+=A,w=0):(y+=u,h+=v,w=1),D=d.get(m,h),0<D||-1===D)C=1;m=0===w?(m-n+(1-A)/2)/r:(h-f+(1-v)/2)/l;p=this.height/m;h=-p/2+this.height/2;p=p/2+this.height/2;n=0===w?f+m*l:n+m*r;n-=Math.floor(n);if(0<D){n=Math.floor(128*n);if(0===w&&0>r||1===w&&0<l)n=128-n-1;n+=128*(D-1);a.drawImage(b.image,n,0,1,128,e,h,1,p-h);1===w&&(a.fillStyle="#000000",a.globalAlpha=.25,a.fillRect(e,h,1,p-h),a.globalAlpha=1)}this._zbuffer[e]=m}this._drawEntities(a)}}};a._drawEntities=function(a){for(var c=this.level.entities,
b=c.length,e=Array(b),d=Array(b),l=g.getTexture(this.textureKey),f=this.camera,h=f.position.x,r=f.position.y,m=0;m<b;++m){var t=c[m].getComponent("transform");e[m]=m;d[m]=(h-t.position.x)*(h-t.position.x)+(r-t.position.y)*(r-t.position.y)}e.sort(function(a,c){return d[c]-d[a]});for(m=0;m<b;++m){var p=c[e[m]];if(p.hasComponent("sprite"))for(var t=p.getComponent("transform"),y=t.position.x-h,z=t.position.y-r,u=1/(f.plane.x*f.direction.y-f.direction.x*f.plane.y),t=u*(-f.plane.y*y+f.plane.x*z),y=Math.round(this.width/
2*(1+u*(f.direction.y*y-f.direction.x*z)/t)),u=Math.abs(Math.round(this.height/t)),z=-u/2+this.height/2,u=u/2+this.height/2,A=Math.abs(Math.round(this.height/t)),v=Math.round(-A/2+y),C=Math.round(A/2+y),p=p.getComponent("sprite");v<C;++v)if(0<t&&0<v&&v<this.width&&t<this._zbuffer[v]){var w=Math.round(128*(v-(-A/2+y))/A),w=w+128*p.texture;a.drawImage(l.image,w,256,1,128,v,~~z,1,~~(u-z))}}}},{"./Node":9,"./assets":10,"math/Vector2":6,"util/object":12}],9:[function(a,d,b){b=d.exports=function(){this.rotation=
this.height=this.width=this.y=this.x=0;this.scaleY=this.scaleX=1;this.color=null};a=b.prototype;a.resize=function(a,b){this.width=a;this.height=b};a.render=function(a){a.save();var c=0!==this.rotation,b=1!==this.scaleX||1!==this.scaleY;if(c||b){var d=this.width/2,f=this.height/2;a.translate(this.x+d,this.y+f);c&&a.rotate(this.rotation);b&&a.scale(this.scaleX,this.scaleY);a.translate(-d,-f)}else a.translate(this.x,this.y);this.color&&(a.fillStyle=this.color,a.fillRect(0,0,this.width,this.height));
this._render(a);a.restore()};a._render=function(){};Object.defineProperty(a,"scale",{set:function(a){this.scaleY=this.scaleX=a}})},{}],10:[function(a,d,b){var c=a("draw/Texture"),e={},h={};b.loadTexture=function(a,b){var d=e[a]=new c;d.on("load",function(c){h[a].width=c.width;h[a].height=c.height});h[a]={texture:d,x:0,y:0,width:0,height:0};d.load(b);return d};b.getTexture=function(a){return e[a]};b.loadTextureAtlas=function(a,c,d){a=b.loadTexture(a,c);for(var e in d)h[e]=d[e],h[e].texture=a};b.getTextureRegion=
function(a){return h[a]}},{"draw/Texture":1}],11:[function(a,d,b){b=d.exports=function(){this._observers={}};a=b.prototype;a.on=function(a,b,d,g){var c=this._observers;Array.isArray(c[a])||(c[a]=[]);c[a].push({callback:b,context:d,once:!!g})};a.emit=function(a){var c=this._observers[a];if(c)for(var b=Array.prototype.slice.call(arguments,1),d=c.length-1;0<=d;--d){var f=c[d];f.callback.apply(f.context,b);f.once&&c.splice(d,1)}}},{}],12:[function(a,d,b){b.extend=function(a,b){a.prototype=new b;a.prototype.constructor=
a;a.superclass=b.prototype;return a.prototype}},{}],13:[function(a,d,b){d.exports={heart:{x:0,y:0,width:16,height:16}}},{}],14:[function(a,d,b){var c=a("input"),e=a("draw");d=a("scene/assets");b=a("scene/FirstPerson");var h=a("./sim/Level"),g=a("./ui/Health");a=a("./atlas");var f=Math.PI/2E3,k=e.createSurface(640,360);k.className="stage pixelated";document.body.appendChild(k);var q=k.getContext("2d"),e=function(){var a=Math.min(window.innerWidth/k.width,window.innerHeight/k.height);k.style.transform=
"scale("+a+", "+a+")";k.style.left=window.innerWidth/2-k.width*a/2+"px";k.style.top=window.innerHeight/2-k.height*a/2+"px"};e();window.addEventListener("resize",e,!1);var x=new h;x.load("level1");c.init();d.loadTextureAtlas("atlas","images/atlas.png",a);d.loadTexture("sprites","images/sprites.png");var B=new b;B.resize(k.width,k.height);B.textureKey="sprites";B.level=x;var l=new g;l.x=4;l.y=4;a=x.player.getComponent("mortal");l.amount=a.health;a.on("healthChange",function(a){l.amount=a});var n=0,
E=function(a){var b=Math.min(a-n,100);n=a;a=x.player.getComponent("transform");c.getKeyState(38)&&x.moveEntity(x.player,.004*b);c.getKeyState(40)&&x.moveEntity(x.player,-.002*b);c.getKeyState(37)&&a.rotate(-f*b);c.getKeyState(39)&&a.rotate(f*b);x.update(b);B.setCamera(a.position.x,a.position.y,a.direction.x,a.direction.y);B.render(q);l.render(q);requestAnimationFrame(E)};E(0)},{"./atlas":13,"./sim/Level":16,"./ui/Health":36,draw:2,input:3,"scene/FirstPerson":8,"scene/assets":10}],15:[function(a,d,
b){var c=a("./prefabs"),e=a("./components"),h=0;a=d.exports=function(a){this.id=h++;this.active=!0;this.type=a;this.level=null;this._components=[];a=c[a];for(var b in a)this.addComponent(b,a[b])};a.prototype.hasComponent=function(a){return this.hasOwnProperty(a)};a.prototype.addComponent=function(a,b){if(!e[a])throw Error("Invalid component: "+a);var c=new e[a](b);c.entity=this;this._components.push(c);this[a]=c};a.prototype.getComponent=function(a){if(this.hasComponent(a))return this[a];throw Error("Entity does not have component: "+
a);};a.prototype.callComponents=function(a){for(var b=[],c=1,d=arguments.length;c<d;c++)b.push(arguments[c]);c=0;for(d=this._components.length;c<d;++c){var e=this._components[c];"function"===typeof e[a]&&e[a].apply(e,b)}}},{"./components":27,"./prefabs":31}],16:[function(a,d,b){var c=a("math/Map"),e=a("math/QuadTree"),h=a("math/collision"),g=a("./Entity"),f=a("./levels"),k={".":0,"#":1},q={"@":"playerStart",b:"bat",L:"lockedDoor",K:"key"};a=d.exports=function(){this.levelKey=null;this.player=new g("player");
this.map=new c;this.quadTree=new e;this.entities=[];this._entityRemoveQueue=[]};a.prototype._buildRoom=function(a,c,b){var d=this.map;a*=15;c*=11;for(var e=0;11>e;++e)for(var l=0;15>l;++l){var f=b[e][l];k.hasOwnProperty(f)?d.set(a+l,c+e,k[f]):q[f]&&(d.set(a+l,c+e,0),f=new g(q[f]),f.getComponent("transform").moveTo(a+l+.5,c+e+.5),this.addEntity(f))}};a.prototype.addEntity=function(a){a.level=this;this.entities.push(a);a.callComponents("add")};a.prototype.removeEntity=function(a){a.active=!1;a.level=
null;this._entityRemoveQueue.push(a)};a.prototype.load=function(a){this.levelKey=a;var c=this.getLevelData(),b=c.layout;a=this.entities;a.length=0;var d=this.map;d.resize(15*b[0].length,11*b.length);d.fill(-1);for(d=0;d<b.length;++d)for(var e=b[d],f=0;f<e.length;++f){var g=e[f];"."!==g&&this._buildRoom(f,d,c.rooms[g])}c=this.player.getComponent("transform");for(b=0;b<a.length;++b)if(d=a[b],"playerStart"===d.type){c.moveToEntity(d);break}c.direction.set(0,-1);this.entities.push(this.player)};a.prototype.getLevelData=
function(){return f[this.levelKey]};a.prototype.update=function(a){var c=this.entities,b=this.quadTree,d=[];b.clear();for(var e=0;e<c.length;++e){var f=c[e];if(f.active&&(f.callComponents("update",a),f.hasComponent("collider"))){var g=f.getComponent("collider").getBoundingBox();g.entity=f;b.insert(g);d.push(f)}}for(a=0;a<d.length;++a)for(c=d[a],e=c.getComponent("collider"),f=e.getBoundingBox(),f=b.retrieve(f),g=0;g<f.length;++g){var h=f[g].entity;if(c.id!==h.id&&e.collidesWithEntity(h)){var k=h.getComponent("collider");
e.trigger||k.trigger?c.callComponents("trigger",h):c.callComponents("collide",h)}}for(b=0;b<this._entityRemoveQueue.length;++b)d=this.entities.indexOf(this._entityRemoveQueue[b]),-1!==d&&this.entities.splice(d,1);this._entityRemoveQueue.length=0};a.prototype._testCircleMapCollision=function(a,c,b){for(var d=Math.floor(a-b),e=Math.ceil(a+b),f=Math.ceil(c+b),g=Math.floor(c-b);g<=f;++g)for(var l=d;l<=e;++l)if(0!==this.map.get(l,g)&&h.testCircleRect(a,c,b,l,g,1,1))return!0;return!1};a.prototype.moveEntity=
function(a,b){var c=a.getComponent("transform"),d=a.getComponent("collider"),e=c.direction.x*b,f=c.direction.y*b;this._testCircleMapCollision(c.position.x+e,c.position.y,d.radius)||(c.position.x+=e);this._testCircleMapCollision(c.position.x,c.position.y+f,d.radius)||(c.position.y+=f)}},{"./Entity":15,"./levels":28,"math/Map":4,"math/QuadTree":5,"math/collision":7}],17:[function(a,d,b){(d.exports=function(a){this.frames=void 0!==a.frames?a.frames:null;this.duration=void 0!==a.duration?a.duration:200;
this._elapsed=this._frameIndex=0}).prototype.update=function(a){this._elapsed+=a;this._elapsed>=this.duration&&(this._elapsed-=this.duration,this._frameIndex=(this._frameIndex+1)%this.frames.length,this.entity.getComponent("sprite").texture=this.frames[this._frameIndex])}},{}],18:[function(a,d,b){var c=a("math/Vector2");d.exports=function(){this.velocity=new c}},{"math/Vector2":6}],19:[function(a,d,b){var c=a("math/collision");a=d.exports=function(a){this.radius=void 0===a.radius?.35:a.radius;this.trigger=
void 0===a.trigger?!1:a.trigger};a.prototype.getBoundingBox=function(){var a=this.entity.getComponent("transform").position,b=this.radius;return{x:a.x-b,y:a.y-b,width:a.x+b,height:a.y+b}};a.prototype.collidesWithEntity=function(a){var b=this.entity.getComponent("transform"),d=a.getComponent("transform");a=a.getComponent("collider");return c.testCircleCircle(b.position.x,b.position.y,this.radius,d.position.x,d.position.y,a.radius)}},{"math/collision":7}],20:[function(a,d,b){a=d.exports=function(a){this.locked=
void 0!==a.locked?a.locked:!1};a.prototype.open=function(){var a=this.entity.level.map,b=this.entity.getComponent("transform");a.set(Math.floor(b.position.x),Math.floor(b.position.y),0)};a.prototype.close=function(){var a=this.entity.level.map,b=this.entity.getComponent("transform");a.set(Math.floor(b.position.x),Math.floor(b.position.y),2)};a.prototype.add=function(){this.close()};a.prototype.trigger=function(a){this.locked?a.hasComponent("inventory")&&(a=a.getComponent("inventory"),a.has("key")&&
(a.remove("key"),this.open())):this.open()}},{}],21:[function(a,d,b){(d.exports=function(a){this.damage=void 0!==a.damage?a.damage:1}).prototype.collide=function(a){a.hasComponent("mortal")&&a.getComponent("mortal").damage(this.damage)}},{}],22:[function(a,d,b){a=d.exports=function(){this.items={}};a.prototype.has=function(a){return 0<this.items[a]};a.prototype.add=function(a){void 0===this.items[a]&&(this.items[a]=0);this.items[a]+=1};a.prototype.remove=function(a){this.has(a)&&--this.items[a]}},
{}],23:[function(a,d,b){b=a("util/object");a=a("util/Emitter");d=d.exports=function(a){this.health=void 0!==a.health?a.health:1};b.extend(d,a);d.prototype.damage=function(a){this.health-=a;this.emit("healthChange",this.health)}},{"util/Emitter":11,"util/object":12}],24:[function(a,d,b){(d.exports=function(a){this.type=void 0!==a.type?a.type:null}).prototype.trigger=function(a){a.hasComponent("inventory")&&(a.getComponent("inventory").add(this.type),this.entity.level.removeEntity(this.entity))}},{}],
25:[function(a,d,b){d.exports=function(a){this.texture=void 0===a.texture?-1:a.texture}},{}],26:[function(a,d,b){var c=a("math/Vector2");a=d.exports=function(){this.position=new c(0,0);this.direction=new c(1,0)};a.prototype.moveTo=function(a,b){this.position.set(a,b)};a.prototype.moveToEntity=function(a){a=a.getComponent("transform");this.moveTo(a.position.x,a.position.y)};a.prototype.rotate=function(a){this.direction.rotate(a)}},{"math/Vector2":6}],27:[function(a,d,b){b.animator=a("./Animator");
b.body=a("./Body");b.collider=a("./Collider");b.door=a("./Door");b.hazard=a("./Hazard");b.inventory=a("./Inventory");b.mortal=a("./Mortal");b.pickup=a("./Pickup");b.sprite=a("./Sprite");b.transform=a("./Transform")},{"./Animator":17,"./Body":18,"./Collider":19,"./Door":20,"./Hazard":21,"./Inventory":22,"./Mortal":23,"./Pickup":24,"./Sprite":25,"./Transform":26}],28:[function(a,d,b){b.level1=a("./level1")},{"./level1":29}],29:[function(a,d,b){d.exports={ceilColor:"#04445C",floorColor:"#008080",layout:"...... ...... IHJ... .GEF.. ..D... .CAB..".split(" "),
rooms:{A:"#######.####### #######L####### ##...........## ##...........## ##...........## ............... ##...........## ##.....@.....## ##...........## ############### ###############".split(" "),B:"############### ############### ##...........## ##.....b.....## ##..##...##..## ....##...##.K## ##..##...##..## ##.....b.....## ##...........## ############### ###############".split(" "),C:"############### ############### ##...........## ##.b.........## ##...........## ##.K..b........ ##...........## ##.b.........## ##...........## ############### ###############".split(" "),
D:"#######.####### #######.####### ##...........## ##...........## ##....###....## ##....###....## ##....###....## ##...........## ##...........## #######.####### #######.#######".split(" "),E:"############### ############### ##...........## ##...........## ##..#.....#..## .......K....... ##..#.....#..## ##...........## ##...........## #######.####### #######.#######".split(" "),F:"############### ############### ##...........## ##..#.....#..## ##...........## .............## ##...........## ##..#.....#..## ##...........## ############### ###############".split(" "),
G:"#######.####### #######L####### ##...........## ##...........## ##....###....## ##....###...... ##....###....## ##...........## ##...........## ############### ###############".split(" "),H:"############### ############### ##...........## ##...........## ##...........## .......#....... ##...........## ##...........## ##...........## #######.####### #######.#######".split(" "),I:"############### ############### ##...........## ##...........## ##...........## ##............. ##...........## ##...........## ##...........## ############### ###############".split(" "),
J:"#######.####### #######.####### ##...........## ##.##.....##.## ##...........## .......#.....L. ##...........## ##.##.....##.## ##...........## ############### ###############".split(" ")}}},{}],30:[function(a,d,b){d.exports={transform:{},collider:{radius:.35},mortal:{},hazard:{},sprite:{},animator:{frames:[0,1],duration:180}}},{}],31:[function(a,d,b){b.bat=a("./bat");b.key=a("./key");b.lockedDoor=a("./lockedDoor");b.player=a("./player");b.playerStart=a("./playerStart")},{"./bat":30,"./key":32,
"./lockedDoor":33,"./player":34,"./playerStart":35}],32:[function(a,d,b){d.exports={transform:{},collider:{radius:.4,trigger:!0},pickup:{type:"key"},sprite:{texture:2}}},{}],33:[function(a,d,b){d.exports={transform:{},collider:{radius:1,trigger:!0},door:{locked:!0}}},{}],34:[function(a,d,b){d.exports={transform:{},collider:{radius:.35},mortal:{health:3},inventory:{}}},{}],35:[function(a,d,b){d.exports={transform:{}}},{}],36:[function(a,d,b){b=a("util/object");var c=a("scene/Node"),e=a("scene/assets");
a=d.exports=function(){c.call(this);this.amount=1};b.extend(a,c);a.prototype._render=function(a){for(var b=e.getTextureRegion("heart"),c=0;c<this.amount;++c)a.drawImage(b.texture.image,b.x,b.y,b.width,b.height,18*c,0,16,16)}},{"scene/Node":9,"scene/assets":10,"util/object":12}]},{},[14]);
