var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,c){var e=this.length||0;0>b&&(b=Math.max(0,e+b));if(null==c||c>e)c=e;c=Number(c);0>c&&(c=Math.max(0,e+c));for(b=Number(b||0);b<c;b++)this[b]=a;return this}},"es6-impl","es3");
(function e$jscomp$0(d,b,c){function e(f,l){if(!b[f]){if(!d[f]){var k="function"==typeof require&&require;if(!l&&k)return k(f,!0);if(g)return g(f,!0);k=Error("Cannot find module '"+f+"'");throw k.code="MODULE_NOT_FOUND",k;}k=b[f]={exports:{}};d[f][0].call(k.exports,function(c){var b=d[f][1][c];return e(b?b:c)},k,k.exports,e$jscomp$0,d,b,c)}return b[f].exports}for(var g="function"==typeof require&&require,f=0;f<c.length;f++)e(c[f]);return e})({1:[function(a,d,b){var c=a("util/object"),e=a("util/Emitter");
b=d.exports=function(){e.call(this);this.height=this.width=0;(this.image=new Image).onload=this._onImageLoad.bind(this)};a=c.extend(b,e);a.load=function(c){this.image.src=c};a._onImageLoad=function(){this.width=this.image.width;this.height=this.image.height;this.emit("load",this)}},{"util/Emitter":11,"util/object":12}],2:[function(a,d,b){b.createSurface=function(c,e){var a=document.createElement("canvas");a.width=c;a.height=e;return a}},{}],3:[function(a,d,b){var c={},e=function(a){c[a.keyCode]=!0},
g=function(a){c[a.keyCode]=!1};b.init=function(){window.addEventListener("keydown",e,!1);window.addEventListener("keyup",g,!1)};b.getKeyState=function(a){return!0===c[a]}},{}],4:[function(a,d,b){b=d.exports=function(a,e){this.cells=[];this.resize(a||0,e||0)};a=b.prototype;a.resize=function(a,e){this.width=a;this.height=e;for(var c=this.cells.length=0;c<e;++c){for(var f=[],b=0;b<a;++b)f.push(0);this.cells.push(f)}};a.get=function(a,e){var c=Math.floor(a),f=Math.floor(e);return 0>c||0>f||c>=this.width||
f>=this.height?-1:this.cells[f][c]};a.set=function(a,e,b){this.cells[e][a]=b};a.fill=function(a){for(var c=0;c<this.height;++c)for(var b=0;b<this.width;++b)this.set(b,c,a)}},{}],5:[function(a,d,b){var c=d.exports=function(a,c,f,b,l,d,w){this.x=a||0;this.y=c||0;this.width=f||1;this.height=b||1;this.depth=l||0;this.depthLimit=d||2;this.rectLimit=w||4;this.children=[];this.rectangles=[]};c.prototype.clear=function(){for(var a=this.children,c=0,f=a.length;c<f;++c)a[c].clear();a.length=0;this.rectangles.length=
0};c.prototype.insert=function(a){var c=this.children,e=this.rectangles;if(0<c.length){var b=this._getInsertIndex(a);-1===b?e.push(a):c[b].insert(a)}else e.push(a),e.length>this.rectLimit&&this.depth<this.depthLimit&&this._divide()};c.prototype.retrieve=function(a){var c=this.rectangles.concat();if(0<this.children.length)for(var e=this._getChildren(a),b=0,l=e.length;b<l;++b)c=c.concat(e[b].retrieve(a));return c};c.prototype._divide=function(){var a=this.children,b=this.rectangles,f=Math.floor(this.width/
2),d=Math.floor(this.height/2),l=this.depth+1;a.push(new c(this.x,this.y,f,d,l,this.depthLimit,this.rectLimit));a.push(new c(this.x+f,this.y,f,d,l,this.depthLimit,this.rectLimit));a.push(new c(this.x,this.y+d,f,d,l,this.depthLimit,this.rectLimit));a.push(new c(this.x+f,this.y+d,f,d,l,this.depthLimit,this.rectLimit));this.rectangles=[];a=0;for(f=b.length;a<f;++a)this.insert(b[a])};c.prototype._getInsertIndex=function(a){var c=Math.floor(this.x+this.width/2),b=Math.floor(this.y+this.height/2);return a.x+
a.width<c?a.y+a.height<b?0:a.y>=b?2:-1:a.x>=c?a.y+a.height<b?1:a.y>=b?3:-1:-1};c.prototype._getChildren=function(a){var c=this.children,b=[],e=Math.floor(this.x+this.width/2),d=Math.floor(this.y+this.height/2);a.x<e&&(a.y<d&&b.push(c[0]),a.y+a.height>=d&&b.push(c[2]));a.x+a.width>=e&&(a.y<d&&b.push(c[1]),a.y+a.height>=d&&b.push(c[3]));return b}},{}],6:[function(a,d,b){b=d.exports=function(a,b){this.set(a||0,b||0)};a=b.prototype;a.set=function(a,b){this.x=a;this.y=b;return this};a.copy=function(a){return this.set(a.x,
a.y)};a.rotate=function(a){return this.set(this.x*Math.cos(a)-this.y*Math.sin(a),this.x*Math.sin(a)+this.y*Math.cos(a))};a.scale=function(a){return this.set(this.x*a,this.y*a)}},{}],7:[function(a,d,b){b.testCircleRect=function(a,b,d,f,k,l,v){l/=2;v/=2;a=Math.abs(a-f-l);b=Math.abs(b-k-v);if(a>l+d||b>v+d)return!1;if(a<=l||b<=v)return!0;k=a-l;b-=v;return k*k+b*b<=d*d};b.testCircleCircle=function(a,b,d,f,k,l){a-=f;b-=k;return d+l>Math.sqrt(a*a+b*b)}},{}],8:[function(a,d,b){var c=a("util/object"),e=a("math/Vector2"),
g=a("./Node"),f=a("./assets");b=d.exports=function(){g.call(this);this._zbuffer=this.textureKey=this.level=null;this.camera={position:new e(0,0),direction:new e(1,0),plane:new e(0,.666)}};a=c.extend(b,g);a.setCamera=function(a,c,b,f){var e=this.camera;e.position.set(a,c);e.direction.set(b,f);e.plane.set(-f,b).scale(.666)};a._render=function(a){if(this.level){var c=this.level.getLevelData();a.fillStyle=c.ceilColor;a.fillRect(0,0,this.width,this.height/2);a.fillStyle=c.floorColor;a.fillRect(0,this.height/
2,this.width,this.height);if(this.level&&this.textureKey){var c=this.camera,b=f.getTexture(this.textureKey),e=this.level.map;this._zbuffer=Array(this.width);var d,n,m,k,q,p,h,g,x,y,r,z,t,C,u,D;for(d=0;d<this.width;++d){n=2*d/this.width-1;m=c.position.x;k=c.position.y;q=c.direction.x+c.plane.x*n;n=c.direction.y+c.plane.y*n;p=Math.floor(m);h=Math.floor(k);y=Math.sqrt(1+n*n/(q*q));r=Math.sqrt(1+q*q/(n*n));u=C=0;0>q?(z=-1,g=(m-p)*y):(z=1,g=(p+1-m)*y);0>n?(t=-1,x=(k-h)*r):(t=1,x=(h+1-k)*r);for(;0===C;)if(g<
x?(g+=y,p+=z,u=0):(x+=r,h+=t,u=1),D=e.get(p,h),0<D||-1===D)C=1;p=0===u?(p-m+(1-z)/2)/q:(h-k+(1-t)/2)/n;g=this.height/p;h=-g/2+this.height/2;g=g/2+this.height/2;m=0===u?k+p*n:m+p*q;m-=Math.floor(m);if(0<D){m=Math.floor(128*m);if(0===u&&0>q||1===u&&0<n)m=128-m-1;m+=128*(D-1);a.drawImage(b.image,m,0,1,128,d,h,1,g-h);1===u&&(a.fillStyle="#000000",a.globalAlpha=.25,a.fillRect(d,h,1,g-h),a.globalAlpha=1)}this._zbuffer[d]=p}this._drawEntities(a)}}};a._drawEntities=function(a){for(var c=this.level.entities,
b=c.length,e=Array(b),d=Array(b),k=f.getTexture(this.textureKey),m=this.camera,g=m.position.x,q=m.position.y,p=0;p<b;++p){var h=c[p].getComponent("transform");e[p]=p;d[p]=(g-h.position.x)*(g-h.position.x)+(q-h.position.y)*(q-h.position.y)}e.sort(function(a,c){return d[c]-d[a]});for(p=0;p<b;++p){var B=c[e[p]];if(B.hasComponent("sprite"))for(var h=B.getComponent("transform"),x=h.position.x-g,y=h.position.y-q,r=1/(m.plane.x*m.direction.y-m.direction.x*m.plane.y),h=r*(-m.plane.y*x+m.plane.x*y),x=Math.round(this.width/
2*(1+r*(m.direction.y*x-m.direction.x*y)/h)),r=Math.abs(Math.round(this.height/h)),y=-r/2+this.height/2,r=r/2+this.height/2,z=Math.abs(Math.round(this.height/h)),t=Math.round(-z/2+x),C=Math.round(z/2+x),B=B.getComponent("sprite");t<C;++t)if(0<h&&0<t&&t<this.width&&h<this._zbuffer[t]){var u=Math.round(128*(t-(-z/2+x))/z),u=u+128*B.texture;a.drawImage(k.image,u,256,1,128,t,~~y,1,~~(r-y))}}}},{"./Node":9,"./assets":10,"math/Vector2":6,"util/object":12}],9:[function(a,d,b){b=d.exports=function(){this.rotation=
this.height=this.width=this.y=this.x=0;this.scaleY=this.scaleX=1;this.color=null};a=b.prototype;a.resize=function(a,b){this.width=a;this.height=b};a.render=function(a){a.save();var b=0!==this.rotation,c=1!==this.scaleX||1!==this.scaleY;if(b||c){var d=this.width/2,k=this.height/2;a.translate(this.x+d,this.y+k);b&&a.rotate(this.rotation);c&&a.scale(this.scaleX,this.scaleY);a.translate(-d,-k)}else a.translate(this.x,this.y);this.color&&(a.fillStyle=this.color,a.fillRect(0,0,this.width,this.height));
this._render(a);a.restore()};a._render=function(){};Object.defineProperty(a,"scale",{set:function(a){this.scaleY=this.scaleX=a}})},{}],10:[function(a,d,b){var c=a("draw/Texture"),e={},g={};b.loadTexture=function(a,b){var d=e[a]=new c;d.on("load",function(b){g[a].width=b.width;g[a].height=b.height});g[a]={texture:d,x:0,y:0,width:0,height:0};d.load(b);return d};b.getTexture=function(a){return e[a]};b.loadTextureAtlas=function(a,c,d){a=b.loadTexture(a,c);for(var e in d)g[e]=d[e],g[e].texture=a};b.getTextureRegion=
function(a){return g[a]}},{"draw/Texture":1}],11:[function(a,d,b){b=d.exports=function(){this._observers={}};a=b.prototype;a.on=function(a,b,d,f){var c=this._observers;Array.isArray(c[a])||(c[a]=[]);c[a].push({callback:b,context:d,once:!!f})};a.emit=function(a){var b=this._observers[a];if(b)for(var c=Array.prototype.slice.call(arguments,1),d=b.length-1;0<=d;--d){var k=b[d];k.callback.apply(k.context,c);k.once&&b.splice(d,1)}}},{}],12:[function(a,d,b){b.extend=function(a,b){a.prototype=new b;a.prototype.constructor=
a;a.superclass=b.prototype;return a.prototype}},{}],13:[function(a,d,b){d.exports={heart:{x:0,y:0,width:16,height:16}}},{}],14:[function(a,d,b){var c=a("input"),e=a("draw");d=a("scene/assets");b=a("scene/FirstPerson");var g=a("./sim/Level"),f=a("./ui/Health");a=a("./atlas");var k=Math.PI/2E3,l=e.createSurface(640,360);l.className="stage pixelated";document.body.appendChild(l);var v=l.getContext("2d"),e=function(){var a=Math.min(window.innerWidth/l.width,window.innerHeight/l.height);l.style.transform=
"scale("+a+", "+a+")";l.style.left=window.innerWidth/2-l.width*a/2+"px";l.style.top=window.innerHeight/2-l.height*a/2+"px"};e();window.addEventListener("resize",e,!1);var w=new g;w.load("level1");c.init();d.loadTextureAtlas("atlas","images/atlas.png",a);d.loadTexture("sprites","images/sprites.png");var A=new b;A.resize(l.width,l.height);A.textureKey="sprites";A.level=w;var n=new f;n.x=4;n.y=4;a=w.player.getComponent("mortal");n.amount=a.health;a.on("healthChange",function(a){n.amount=a});var m=0,
E=function(a){var b=Math.min(a-m,100);m=a;a=w.player.getComponent("transform");c.getKeyState(38)&&w.moveEntity(w.player,.004*b);c.getKeyState(40)&&w.moveEntity(w.player,-.002*b);c.getKeyState(37)&&a.rotate(-k*b);c.getKeyState(39)&&a.rotate(k*b);w.update(b);A.setCamera(a.position.x,a.position.y,a.direction.x,a.direction.y);A.render(v);n.render(v);requestAnimationFrame(E)};E(0)},{"./atlas":13,"./sim/Level":16,"./ui/Health":31,draw:2,input:3,"scene/FirstPerson":8,"scene/assets":10}],15:[function(a,d,
b){var c=a("./prefabs"),e=a("./components"),g=0;a=d.exports=function(a){this.id=g++;this.type=a;this._components=[];a=c[a];for(var b in a)this.addComponent(b,a[b])};a.prototype.hasComponent=function(a){return this.hasOwnProperty(a)};a.prototype.addComponent=function(a,b){if(!e[a])throw Error("Invalid component: "+a);var c=new e[a](b);c.entity=this;this._components.push(c);this[a]=c};a.prototype.getComponent=function(a){if(this.hasComponent(a))return this[a];throw Error("Entity does not have component: "+
a);};a.prototype.callComponents=function(a){for(var b=[],c=1,d=arguments.length;c<d;c++)b.push(arguments[c]);c=0;for(d=this._components.length;c<d;++c){var e=this._components[c];"function"===typeof e[a]&&e[a].apply(e,b)}}},{"./components":24,"./prefabs":28}],16:[function(a,d,b){var c=a("math/Map"),e=a("math/QuadTree"),g=a("math/collision"),f=a("./Entity"),k=a("./levels"),l={".":0,"#":1},v={"@":"playerStart",b:"bat"};a=d.exports=function(){this.levelKey=null;this.player=new f("player");this.map=new c;
this.quadTree=new e;this.entities=[]};a.prototype._buildRoom=function(a,b,c){var d=this.map,e=this.entities;a*=15;b*=11;for(var n=0;11>n;++n)for(var g=0;15>g;++g){var h=c[n][g];l.hasOwnProperty(h)?d.set(a+g,b+n,l[h]):v[h]&&(d.set(a+g,b+n,0),h=new f(v[h]),h.getComponent("transform").moveTo(a+g+.5,b+n+.5),e.push(h))}};a.prototype.load=function(a){this.levelKey=a;var b=this.getLevelData(),c=b.layout;a=this.entities;a.length=0;var d=this.map;d.resize(15*c[0].length,11*c.length);d.fill(-1);for(d=0;d<c.length;++d)for(var e=
c[d],f=0;f<e.length;++f){var g=e[f];"."!==g&&this._buildRoom(f,d,b.rooms[g])}b=this.player.getComponent("transform");for(c=0;c<a.length;++c)if(d=a[c],"playerStart"===d.type){b.moveToEntity(d);break}b.direction.set(0,-1);this.entities.push(this.player)};a.prototype.getLevelData=function(){return k[this.levelKey]};a.prototype.update=function(a){var b=this.entities,c=this.quadTree,d=[];c.clear();for(var e=0;e<b.length;++e){var f=b[e];f.callComponents("update",a);if(f.hasComponent("collider")){var g=
f.getComponent("collider").getBoundingBox();g.entity=f;c.insert(g);d.push(f)}}for(a=0;a<d.length;++a)for(b=d[a],e=b.getComponent("collider"),f=e.getBoundingBox(),f=c.retrieve(f),g=0;g<f.length;++g){var h=f[g].entity;b.id!==h.id&&e.collidesWithEntity(h)&&(e.trigger?b.callComponents("trigger",h):b.callComponents("collide",h))}};a.prototype._testCircleMapCollision=function(a,b,c){for(var d=Math.floor(a-c),e=Math.ceil(a+c),f=Math.ceil(b+c),k=Math.floor(b-c);k<=f;++k)for(var h=d;h<=e;++h)if(0!==this.map.get(h,
k)&&g.testCircleRect(a,b,c,h,k,1,1))return!0;return!1};a.prototype.moveEntity=function(a,b){var c=a.getComponent("transform"),d=a.getComponent("collider"),e=c.direction.x*b,f=c.direction.y*b;this._testCircleMapCollision(c.position.x+e,c.position.y,d.radius)||(c.position.x+=e);this._testCircleMapCollision(c.position.x,c.position.y+f,d.radius)||(c.position.y+=f)}},{"./Entity":15,"./levels":25,"math/Map":4,"math/QuadTree":5,"math/collision":7}],17:[function(a,d,b){(d.exports=function(a){this.frames=
void 0!==a.frames?a.frames:null;this.duration=void 0!==a.duration?a.duration:200;this._elapsed=this._frameIndex=0}).prototype.update=function(a){this._elapsed+=a;this._elapsed>=this.duration&&(this._elapsed-=this.duration,this._frameIndex=(this._frameIndex+1)%this.frames.length,this.entity.getComponent("sprite").texture=this.frames[this._frameIndex])}},{}],18:[function(a,d,b){var c=a("math/Vector2");d.exports=function(){this.velocity=new c}},{"math/Vector2":6}],19:[function(a,d,b){var c=a("math/collision");
a=d.exports=function(a){this.radius=void 0===a.radius?.35:a.radius;this.trigger=void 0===a.trigger?!1:a.trigger};a.prototype.getBoundingBox=function(){var a=this.entity.getComponent("transform").position,b=this.radius;return{x:a.x-b,y:a.y-b,width:a.x+b,height:a.y+b}};a.prototype.collidesWithEntity=function(a){var b=this.entity.getComponent("transform"),d=a.getComponent("transform");a=a.getComponent("collider");return c.testCircleCircle(b.position.x,b.position.y,this.radius,d.position.x,d.position.y,
a.radius)}},{"math/collision":7}],20:[function(a,d,b){(d.exports=function(a){this.damage=void 0!==a.damage?a.damage:1}).prototype.collide=function(a){a.hasComponent("mortal")&&a.getComponent("mortal").damage(this.damage)}},{}],21:[function(a,d,b){b=a("util/object");a=a("util/Emitter");d=d.exports=function(a){this.health=void 0!==a.health?a.health:1};b.extend(d,a);d.prototype.damage=function(a){this.health-=a;this.emit("healthChange",this.health)}},{"util/Emitter":11,"util/object":12}],22:[function(a,
d,b){d.exports=function(a){this.texture=void 0===a.texture?-1:a.texture}},{}],23:[function(a,d,b){var c=a("math/Vector2");a=d.exports=function(){this.position=new c(0,0);this.direction=new c(1,0)};a.prototype.moveTo=function(a,b){this.position.set(a,b)};a.prototype.moveToEntity=function(a){a=a.getComponent("transform");this.moveTo(a.position.x,a.position.y)};a.prototype.rotate=function(a){this.direction.rotate(a)}},{"math/Vector2":6}],24:[function(a,d,b){b.animator=a("./Animator");b.body=a("./Body");
b.collider=a("./Collider");b.hazard=a("./Hazard");b.mortal=a("./Mortal");b.sprite=a("./Sprite");b.transform=a("./Transform")},{"./Animator":17,"./Body":18,"./Collider":19,"./Hazard":20,"./Mortal":21,"./Sprite":22,"./Transform":23}],25:[function(a,d,b){b.level1=a("./level1")},{"./level1":26}],26:[function(a,d,b){d.exports={ceilColor:"#04445C",floorColor:"#008080",layout:"...... ...... IHJ... .GEF.. ..D... .CAB..".split(" "),rooms:{A:"#######.####### #######.####### ##...........## ##...........## ##...........## ............... ##...........## ##.....@.....## ##...........## ############### ###############".split(" "),
B:"############### ############### ##...........## ##.....b.....## ##..##...##..## ....##...##..## ##..##...##..## ##.....b.....## ##...........## ############### ###############".split(" "),C:"############### ############### ##...........## ##.b.........## ##...........## ##....b........ ##...........## ##.b.........## ##...........## ############### ###############".split(" "),D:"#######.####### #######.####### ##...........## ##...........## ##....###....## ##....###....## ##....###....## ##...........## ##...........## #######.####### #######.#######".split(" "),
E:"############### ############### ##...........## ##...........## ##..#.....#..## ............... ##..#.....#..## ##...........## ##...........## #######.####### #######.#######".split(" "),F:"############### ############### ##...........## ##..#.....#..## ##...........## .............## ##...........## ##..#.....#..## ##...........## ############### ###############".split(" "),G:"#######.####### #######.####### ##...........## ##...........## ##....###....## ##....###...... ##....###....## ##...........## ##...........## ############### ###############".split(" "),
H:"############### ############### ##...........## ##...........## ##...........## .......#....... ##...........## ##...........## ##...........## #######.####### #######.#######".split(" "),I:"############### ############### ##...........## ##...........## ##...........## ##............. ##...........## ##...........## ##...........## ############### ###############".split(" "),J:"#######.####### #######.####### ##...........## ##.##.....##.## ##...........## .......#....... ##...........## ##.##.....##.## ##...........## ############### ###############".split(" ")}}},
{}],27:[function(a,d,b){d.exports={transform:{},collider:{radius:.35},mortal:{},hazard:{},sprite:{},animator:{frames:[0,1],duration:180}}},{}],28:[function(a,d,b){b.bat=a("./bat");b.player=a("./player");b.playerStart=a("./playerStart")},{"./bat":27,"./player":29,"./playerStart":30}],29:[function(a,d,b){d.exports={transform:{},collider:{radius:.35},mortal:{health:3}}},{}],30:[function(a,d,b){d.exports={transform:{}}},{}],31:[function(a,d,b){b=a("util/object");var c=a("scene/Node"),e=a("scene/assets");
a=d.exports=function(){c.call(this);this.amount=1};b.extend(a,c);a.prototype._render=function(a){for(var b=e.getTextureRegion("heart"),c=0;c<this.amount;++c)a.drawImage(b.texture.image,b.x,b.y,b.width,b.height,18*c,0,16,16)}},{"scene/Node":9,"scene/assets":10,"util/object":12}]},{},[14]);
